language: ruby
cache: bundler
rvm:
  - 2.6.3
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database gotboard2_test;' -U postgres
script:
  - bundle exec rake --trace spec
services:
  - postgresql
