version: "2"

services:
  api:
    #image: got-api:v1.0.0
    build: ./
    volumes:
      - ./:/app
    command: bash -c "bundle && rake db:setup && source .env && rails s"
    ports:
      - "3000:3000"
    links:
      - "db"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: gotboard
    stdin_open: true
    tty: true

  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gotboard
